language: python

python:
  - '3.4'
  - '2.7'

env:
  - DJANGO_VERSION=1.8.2
  - DJANGO_VERSION=1.9.5

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - example/manage.py test
